apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-nuwas-req-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - forwardOriginalToken: true
    issuer: https://tt.nuwas.nn/keycloak/realms/nuwas-auth
    jwksUri: http://keycloak.jwt-keycloak.svc.cluster.local:8080/keycloak/realms/nuwas-auth/protocol/openid-connect/certs
